#!/usr/bin/env bash
exec "$@"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $DB_NAME;
    CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD' CREATEDB;
    GRANT ALL ON DATABASE $DB_NAME to "$DB_USER";
EOSQL
